# Generated by Django 5.1.6 on 2025-02-12 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=100)),
                ("setor", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("senha", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("telefone", models.CharField(max_length=11)),
                ("endereco", models.CharField(max_length=500)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empresa",
                        to="core.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Financa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=100)),
                ("valor", models.CharField(max_length=11)),
                ("cliente", models.ManyToManyField(blank=True, to="core.cliente")),
                ("empresa", models.ManyToManyField(blank=True, to="core.empresa")),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=100)),
                ("total", models.CharField(max_length=100)),
                ("cliente", models.ManyToManyField(blank=True, to="core.cliente")),
                ("empresa", models.ManyToManyField(blank=True, to="core.empresa")),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_prod", models.CharField(max_length=100)),
                ("preco_prod", models.CharField(max_length=11)),
                ("descricao_prod", models.CharField(max_length=500)),
                ("empresa", models.ManyToManyField(blank=True, to="core.empresa")),
            ],
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=100)),
                ("preco", models.CharField(max_length=11)),
                ("empresa", models.ManyToManyField(blank=True, to="core.empresa")),
            ],
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.CharField(max_length=10)),
                ("preco_uni", models.CharField(max_length=11)),
                ("pedido", models.ManyToManyField(blank=True, to="core.pedido")),
                ("produto", models.ManyToManyField(blank=True, to="core.produto")),
                ("servico", models.ManyToManyField(blank=True, to="core.servico")),
            ],
        ),
        migrations.AddField(
            model_name="empresa",
            name="Usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuario",
                to="core.usuario",
            ),
        ),
    ]
