# Generated by Django 5.1.6 on 2025-02-17 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=100)),
                ("setor", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="financa",
            name="empresa",
        ),
        migrations.AddField(
            model_name="servico",
            name="cliente",
            field=models.ManyToManyField(blank=True, to="core.cliente"),
        ),
        migrations.AddField(
            model_name="cliente",
            name="fornecedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fornecedor",
                to="core.fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="financa",
            name="Fornecedor",
            field=models.ManyToManyField(blank=True, to="core.fornecedor"),
        ),
        migrations.AddField(
            model_name="produto",
            name="fornecedor",
            field=models.ManyToManyField(blank=True, to="core.fornecedor"),
        ),
        migrations.DeleteModel(
            name="Empresa",
        ),
    ]
