# Generated by Django 5.1.6 on 2025-02-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_fornecedor_remove_pedido_empresa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_func", models.CharField(max_length=100)),
                ("funcao_func", models.CharField(max_length=100)),
                ("salario_func", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_admissao_func", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
