# Generated by Django 5.1.6 on 2025-02-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_funcionario"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="quantidade_prod",
            field=models.IntegerField(default=0),
        ),
    ]
