# Generated by Django 5.1.6 on 2025-02-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_produto_quantidade_prod"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itempedido",
            name="pedido",
        ),
        migrations.RemoveField(
            model_name="itempedido",
            name="produto",
        ),
        migrations.RemoveField(
            model_name="itempedido",
            name="servico",
        ),
        migrations.RenameField(
            model_name="cliente",
            old_name="endereco",
            new_name="endereco_cliente",
        ),
        migrations.RenameField(
            model_name="cliente",
            old_name="nome",
            new_name="nome_cliente",
        ),
        migrations.RenameField(
            model_name="cliente",
            old_name="telefone",
            new_name="telefone_cliente",
        ),
        migrations.RenameField(
            model_name="servico",
            old_name="descricao",
            new_name="tipo_os",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="email",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="fornecedor",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="nome",
        ),
        migrations.AddField(
            model_name="cliente",
            name="email_cliente",
            field=models.EmailField(default="exemplo@email.com", max_length=254),
        ),
        migrations.AddField(
            model_name="servico",
            name="endereço_solicitante",
            field=models.CharField(default="Endereço não informado", max_length=500),
        ),
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_orca", models.DateField()),
                ("endereco_orca", models.CharField(max_length=555)),
                ("preco_orca", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cliente", models.ManyToManyField(blank=True, to="core.cliente")),
                ("produto", models.ManyToManyField(blank=True, to="core.produto")),
            ],
        ),
        migrations.DeleteModel(
            name="Financa",
        ),
        migrations.DeleteModel(
            name="ItemPedido",
        ),
    ]
