# Generated by Django 5.1.6 on 2025-02-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_itempedido_pedido_remove_itempedido_produto_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servico",
            name="endereço_solicitante",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="preco",
        ),
        migrations.AddField(
            model_name="servico",
            name="orcamento",
            field=models.ManyToManyField(blank=True, to="core.orcamento"),
        ),
    ]
