# Generated by Django 5.1.6 on 2025-02-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_servico_endereço_solicitante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="data_os",
            field=models.DateField(blank=True, null=True),
        ),
    ]
