# Generated by Django 5.1.6 on 2025-02-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_servico_data_os"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servico",
            old_name="data_os",
            new_name="data_emissao",
        ),
        migrations.RenameField(
            model_name="servico",
            old_name="tipo_os",
            new_name="tipo_servico",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="orcamento",
        ),
        migrations.AddField(
            model_name="servico",
            name="data_entrega",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="produto_utilizado",
            field=models.ManyToManyField(null=True, to="core.produto"),
        ),
    ]
