# Generated by Django 5.1.6 on 2025-02-19 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_data_os_servico_data_emissao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orcamento",
            name="servico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="servico",
                to="core.servico",
            ),
        ),
        migrations.CreateModel(
            name="OrdemServico",
            fields=[
                ("codigo_os", models.AutoField(primary_key=True, serialize=False)),
                ("data_os", models.DateField()),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clientes",
                        to="core.cliente",
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orcamento",
                        to="core.orcamento",
                    ),
                ),
                ("servico", models.ManyToManyField(blank=True, to="core.servico")),
            ],
        ),
        migrations.DeleteModel(
            name="Pedido",
        ),
    ]
