# Generated by Django 5.1.6 on 2025-02-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_orcamento_servico_ordemservico_delete_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servico",
            name="produto_utilizado",
            field=models.ManyToManyField(blank=True, to="core.produto"),
        ),
    ]
