# Generated by Django 5.1.6 on 2025-02-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_servico_produto_utilizado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orcamento",
            name="endereco_orca",
        ),
    ]
