# Generated by Django 5.1.6 on 2025-03-18 01:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_orcamento_cliente_alter_ordemservico_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_budget', models.DateField()),
                ('price_budget', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpfcnpj_customer', models.CharField(blank=True, max_length=18, null=True)),
                ('name_customer', models.CharField(max_length=100)),
                ('fantasyName_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('email_customer', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone_customer', models.CharField(blank=True, max_length=15, null=True)),
                ('cep_customer', models.CharField(blank=True, max_length=9, null=True)),
                ('address_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('homeNumber_customer', models.CharField(blank=True, max_length=10, null=True)),
                ('neighborhood_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('city_customer', models.CharField(blank=True, max_length=50, null=True)),
                ('state_customer', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_employee', models.CharField(max_length=100)),
                ('cpf_employee', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(code='invalid_cpf', message='O CPF deve estar no formato 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('email_employee', models.EmailField(blank=True, max_length=254, null=True)),
                ('job_employee', models.CharField(max_length=100)),
                ('salary_employee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accountNumber_employee', models.CharField(blank=True, max_length=20, null=True)),
                ('agency_employee', models.CharField(blank=True, max_length=6, null=True)),
                ('admissionDate_employee', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100)),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_product', models.IntegerField(default=0)),
                ('description_product', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueDate_service', models.DateField(blank=True, null=True)),
                ('deliveryDate_service', models.DateField(blank=True, null=True)),
                ('typeService_service', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service_customer', to='core.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_serviceOrder', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='servico',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='fornecedor',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='orcamento',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='produto_utilizado',
        ),
        migrations.AddField(
            model_name='budget',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Budget_customers', to='core.customer'),
        ),
        migrations.AddField(
            model_name='budget',
            name='product',
            field=models.ManyToManyField(blank=True, to='core.product'),
        ),
        migrations.AddField(
            model_name='budget',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Budget_service', to='core.service'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ServiceOrder_budget', to='core.budget'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ServiceOrder_customer', to='core.customer'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='service',
            field=models.ManyToManyField(blank=True, to='core.service'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
        migrations.DeleteModel(
            name='Orcamento',
        ),
        migrations.DeleteModel(
            name='OrdemServico',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
