# Generated by Django 5.1.6 on 2025-03-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_budget_customer_employee_product_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_supplier', models.CharField(max_length=100)),
                ('description_supplier', models.CharField(max_length=100)),
                ('sector_supplier', models.CharField(max_length=100)),
            ],
        ),
    ]
