# Generated by Django 5.1.6 on 2025-03-20 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_service_quantity_remove_service_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceorder",
            name="service",
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ServiceOrder_service",
                to="core.service",
            ),
        ),
    ]
