# Generated by Django 5.1.6 on 2025-03-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_serviceorder_service_serviceorder_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="date_budget",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_product",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
