# Generated by Django 5.1.7 on 2025-03-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_passage_id_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.CharField(default=1, help_text='Passage ID', max_length=255, verbose_name='passage_id'),
        ),
    ]
