# Generated by Django 5.1.7 on 2025-03-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_user_passage_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="passage_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
